### PR TITLE
check for NULL

### PR DESCRIPTION
**Pull request by mwotton**
This makes it usable with FTS4 tables.

### CODE REVIEW

**Comment by salviati** [comment]
Thanks!

**Comment by mwotton** [comment]
I am still getting some errors with my real tables, but I haven't quite tracked it down yet. Will lodge another issue if i find it.

**Comment by salviati** [comment]
Sure. I'm closing #1 BTW.

**Comment by mwotton** [comment]
yes, i should have included a link in the PR :) sorry

**Pull request merged**
